# DataSource Config
spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://39.108.5.84:3306/db_bpmn?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver